//
//  SeemtPermission.swift
//  Techres-Seemt
//
//  Created by Kelvin on 18/04/2023.
//  Copyright © 2023 OVERATE-VNTECH. All rights reserved.
//

import UIKit

enum PERMISSIONS : String{
    
    case OWNER = "OWNER"
    case VIEW_ALL = "VIEW_ALL"
    case CHECK_KPI_TASK_MANAGER = "CHECK_KPI_TASK_MANAGER"
    case APPROVE_EMPLOYEE_TARGET = "APPROVE_EMPLOYEE_TARGET"
    case JOB_MANAGER = "JOB_MANAGER"
    case APPROVE_EMPLOYEE_ADVANCE_SALARY = "APPROVE_EMPLOYEE_ADVANCE_SALARY"
    case CHECK_KPI_TASK_ALL_EMPLOYEE = "CHECK_KPI_TASK_ALL_EMPLOYEE"
    case APPROVE_EMPLOYEE_ADDITION_SALARY = "APPROVE_EMPLOYEE_ADDITION_SALARY"
    case RESTAURANT_MANAGER = "RESTAURANT_MANAGER"// QUẢN LÝ TỔNG CÁC CHI NHÁNH TQL 
    case DAILY_CHECK_GOODS_INVENTORY = "DAILY_CHECK_GOODS_INVENTORY"
    case DAILY_CHECK_FOOD_INVENTORY = "DAILY_CHECK_FOOD_INVENTORY"
    case EMPLOYEE_LEAVE_FORM_MANAGER = "EMPLOYEE_LEAVE_FORM_MANAGER"
    case BRAND_MANAGER = "BRAND_MANAGER"
    case GENERAL_MANAGER = "GENERAL_MANAGER"
    case BOOKING_MANAGEMENT = "BOOKING_MANAGEMENT"
    case CHEF_MANAGER = "CHEF_MANAGER"
    case ACCOUNTING_MANAGER = "ACCOUNTING_MANAGER"
    case SALARY_MANAGER = "SALARY_MANAGER"
    case APPROVE_SALARY_TABLE = "APPROVE_SALARY_TABLE"
    case CONFIRM_SALARY_TABLE = "CONFIRM_SALARY_TABLE"
    case TMS_VIEW_EMPLOYEE_SALARY = "TMS_VIEW_EMPLOYEE_SALARY"
    case EMPLOYEE_KAIZEN_MANAGER = "EMPLOYEE_KAIZEN_MANAGER"
    case CASHIER = "CASHIER"
    case WAITER = "WAITER"
    case STOREKEEPER = "STOREKEEPER"
    case COOKER = "COOKER"
    case BEERKEEPER = "BEERKEEPER"
    case MARKETING = "MARKETING"
    case AREA_LEADER = "AREA_LEADER"
    case VICE_MANAGER = "VICE_MANAGER"
    case CHIEF_ACCOUNTANT = "CHIEF_ACCOUNTANT"
    case ACCOUNTANT = "ACCOUNTANT"
    case BRANCH_MANAGER = "BRANCH_MANAGER"

    case EMPLOYEE_MANAGER = "EMPLOYEE_MANAGER"
    case COOKING_MANAGER = "COOKING_MANAGER"
    case CANCEL_COMPLETED_FOOD = "CANCEL_COMPLETED_FOOD"
    case CANCEL_DRINK = "CANCEL_DRINK"
    case DISCOUNT_FOOD = "DISCOUNT_FOOD"
    case AREA_TABLE_MANAGER = "AREA_TABLE_MANAGER"
    case DISCOUNT_ORDER = "DISCOUNT_ORDER"
    case GIFT_FOOD = "GIFT_FOOD"
    case ADD_CUSTOM_FOOD = "ADD_CUSTOM_FOOD"
    case BBQ_KITCHEN_MANAGER = "BBQ_KITCHEN_MANAGER"
    case TASK_MANAGER = "TASK_MANAGER"
    case FOOD_MANAGER = "FOOD_MANAGER"
    case DRINK_MANAGER = "DRINK_MANAGER"
    case TMS_SALARY_TARGET_AND_RANKING_BOARD = "TMS_SALARY_TARGET_AND_RANKING_BOARD"
    case MASTER_CHEF_BONUS_FOOD_REVIEW = "MASTER_CHEF_BONUS_FOOD_REVIEW"
    case CHEF_BONUS_FOOD_REVIEW = "CHEF_BONUS_FOOD_REVIEW"
    case CONFIRM_EMPLOYEE_ADDITION_SALARY = "CONFIRM_EMPLOYEE_ADDITION_SALARY"
    case MANAGER_EMPLOYEE_ADDITION_SALARY = "MANAGER_EMPLOYEE_ADDITION_SALARY"
    case TMS_CHAT_GROUP_MANAGER = "TMS_CHAT_GROUP_MANAGER"
    case ACCOUNTANT_ACCESS = "ACCOUNTANT_ACCESS"
    case SUBMIT_SUPPLEMENTARY_OTHER_MATERIAL_INVENTORY = "SUBMIT_SUPPLEMENTARY_OTHER_MATERIAL_INVENTORY"
    case SUBMIT_SUPPLEMENTARY_INTERNAL_MATERIAL_INVENTORY = "SUBMIT_SUPPLEMENTARY_INTERNAL_MATERIAL_INVENTORY"
    case SUBMIT_SUPPLEMENTARY_GOODS_MATERIAL_INVENTORY = "SUBMIT_SUPPLEMENTARY_GOODS_MATERIAL_INVENTORY"
    case SUBMIT_SUPPLEMENTARY_FOOD_MATERIAL_INVENTORY = "SUBMIT_SUPPLEMENTARY_FOOD_MATERIAL_INVENTORY"
    
    case REPORT_DASHBOARD_DAILY_ACTIVITY = "REPORT_DASHBOARD_DAILY_ACTIVITY"
    case REPORT_DASHBOARD_REVENUE_COST_PROFIT = "REPORT_DASHBOARD_REVENUE_COST_PROFIT"
    case REPORT_DASHBOARD_REVENUE = "REPORT_DASHBOARD_REVENUE"
    case REPORT_DASHBOARD_COST = "REPORT_DASHBOARD_COST"
    case REPORT_DASHBOARD_PROFIT = "REPORT_DASHBOARD_PROFIT"
    case REPORT_DASHBOARD_PAY_DEBT = "REPORT_DASHBOARD_PAY_DEBT"
    case REPORT_DASHBOARD_REAL_PROFIT = "REPORT_DASHBOARD_REAL_PROFIT"
    case REPORT_DASHBOARD_REVENUE_BY_FOOD_AND_GOODS = "REPORT_DASHBOARD_REVENUE_BY_FOOD_AND_GOODS"
    case REPORT_DASHBOARD_REVENUE_BY_AREA = "REPORT_DASHBOARD_REVENUE_BY_AREA"
    case REPORT_DASHBOARD_EXTRA_CHARGE = "REPORT_DASHBOARD_EXTRA_CHARGE"
    case REPORT_DASHBOARD_PROFIT_BY_FOOD_AND_GOODS = "REPORT_DASHBOARD_PROFIT_BY_FOOD_AND_GOODS"
    case REPORT_DASHBOARD_SALES = "REPORT_DASHBOARD_SALES"
    
    case REPORT_DASHBOARD_CUSTOMER = "REPORT_DASHBOARD_CUSTOMER"
    case BYPASS_CHECKIN = "BYPASS_CHECKIN"
    case WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER"
    case BAR_ACCESS = "BAR_ACCESS"
    case INVENTORY_MATERIAL_REQUEST = "INVENTORY_MATERIAL_REQUEST"
    
    
    case REPORT_MANAGER = "REPORT_MANAGER"
    case REPORT_DRINK = "REPORT_DRINK"
    case REPORT_GIFT_FOOD = "REPORT_GIFT_FOOD"
    case REPORT_FOOD = "REPORT_FOOD"
    case REPORT_DISCOUNT = "REPORT_DISCOUNT"
    case REPORT_VAT = "REPORT_VAT"
    case REPORT_OTHER_FOOD = "REPORT_OTHER_FOOD"
    case REPORT_CANCEL_FOOD = "REPORT_CANCEL_FOOD"
    case BRANCH_INVENTORY_MANAGEMENT = "BRANCH_INVENTORY_MANAGEMENT" // Quản lý kho chi nhánh
    case APPROVE_EMPLOYEE_FORM = "APPROVE_EMPLOYEE_FORM" // Duyệt các loại đơn
    case EMPLOYEE_CHECKIN_LIST = "EMPLOYEE_CHECKIN_LIST" // Tạm khóa nv || Xem danh sách nv || Xem ds chấm công
    case PAYROLL_OVERVIEW = "PAYROLL_OVERVIEW" // duyệt bảng lương nhân viên cấp dưới
    case GOODS_INVENTORY_MANAGEMENT = "GOODS_INVENTORY_MANAGEMENT" // Quản lý nhập kho hàng hoá
    case KAIZEN_MANAGEMENT = "KAIZEN_MANAGEMENT" // duyệt từ chối kaizen
}
